name: Website Mirror
on: 
  issues:
    types: [opened]
jobs:
    build:
        name: Setup Environment for Mirroring
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./
               env:
                  URL: www.mindiverse.foundation
                  _GITHUB_TOKEN: b30a41d1a10c18afbd80bd49b5be1878fed09fda
                  USER_NAME: CicoZhang
                  USER_EMAIL: cncico@gmail.com
