name: Website Mirror
on: 
  issues:
    types: [opened]
jobs:
    build:
        name: Setup Environment for Mirroring
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./
               env:
                  URL: www.mindiverse.foundation
                  _GITHUB_TOKEN: b997521dac912c3f4d5f4bf8e55ccba49f2648d1
                  USER_NAME: CicoZhang
                  USER_EMAIL: cncico@gmail.com
