name: Website Mirror
on: 
  issues:
    types: [opened]
jobs:
    build:
        name: Setup Environment for Mirroring
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./
               env:
                  URL: www.mindiverse.foundation
                  _GITHUB_TOKEN: 65e8a154d6790135a0aad7e62ff6ad50e929960b
                  USER_NAME: CicoZhang
                  USER_EMAIL: cncico@gmail.com
